apiVersion: v1
kind: Service
metadata:
  name: aksdemo-app-service2
  labels:
    app: aksdemo-app2
spec:
  type: LoadBalancer
  selector:
    app: aksdemo-app2
  ports:
    - port: 80
      targetPort: 8080
